apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mft-kube-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mqft-kube
    spec:
      containers:
      - name: agentsrc
        image: registry.eu-de.bluemix.net/mft-images/agentredist_mftimagerepo:1.0
        env:
        - name: MQ_QMGR_NAME
          value: "QM1"
        - name: MQ_QMGR_HOST
          value: "QMgr Host name"
        - name: MQ_QMGR_PORT
          value: "QMgr port"
        - name: MQ_QMGR_CHL
          value: "QMgr SVRCONN Channel"
        - name: MFT_AGENT_NAME
          value: "AGENTSRC"
        - name: IS_PBA_AGENT
          value: "true"
        - name: PROTOCOL_FILE_SERVER_TYPE
          value: ""
        - name: SERVER_HOST_NAME
          value: ""
        - name: SERVER_TIME_ZONE
          value: ""
        - name: SERVER_PLATFORM
          value: ""
        - name: SERVER_LOCALE
          value: ""
        - name: SERVER_FILE_ENCODING
          value: ""
