kind: ConfigMap
apiVersion: v1
metadata:
  name: mqmft-agent-config
  namespace: ibmmqmft
data:
  mqmftcfg.json: >
    {"waitTimeToStart":10,"coordinationQMgr":{"name":"QUICKSTART","host":"172.30.252.35","port":1414,"channel":"QS_SVRCONN","additionalProperties"
    :
    {}},"commandQMgr":{"name":"QUICKSTART","host":"172.30.252.35","port":1414,"channel":"QS_SVRCONN","additionalProperties"
    :
    {}},"agents":[{"name":"ATCFG","type":"STANDARD","qmgrName":"QUICKSTART","qmgrHost":"172.30.252.35","qmgrPort":1414,"qmgrChannel":"QS_SVRCONN","additionalProperties":{"enableQueueInputOutput":"true","logCapture":"true"}},{"name":"KXAGNT","type":"STANDARD","qmgrName":"QUICKSTART","qmgrHost":"172.30.252.35","qmgrPort":1414,"qmgrChannel":"QS_SVRCONN","additionalProperties":{"enableQueueInputOutput":"true"}},{"name":"KYAGNT","type":"STANDARD","qmgrName":"QUICKSTART","qmgrHost":"172.30.252.35","qmgrPort":1414,"qmgrChannel":"QS_SVRCONN","additionalProperties":{"enableQueueInputOutput":"true","logCapture":"true","agentQMgrAuthenticationCredentialsFile":"/mqmftcred/agentcreds/MQMFTCredentials.xml"}},{"name":"BRIDGE","type":"BRIDGE","qmgrName":"QUICKSTART","qmgrHost":"172.30.252.35","qmgrPort":1414,"qmgrChannel":"QS_SVRCONN","protocolBridge"
    :
    {"serverType":"SFTP","serverHost":"10.17.68.52","serverPlatform":"UNIX","serverLocale":"en-GB","listFormat"="UNIX",
    "limitedWrite"="false", "serverFileEncoding"="UTF8", "passiveMode"="true",
    "protocolBridgeProperties" : {}},
    "additionalProperties":{"logCapture":"true","enableQueueInputOutput":"false","protocolBridgeCredentialConfiguration":"/mqmftbridgecred/agentcreds/ProtocolBridgeCredentials.prop"}}]}
