kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mymftpvc
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-s3fs-standard-regional"
    ibm.io/endpoint: "https://s3.eu-de.objectstorage.service.networklayer.com"
    ibm.io/region: "eu-de"
    ibm.io/auto-create-bucket: "false"
    ibm.io/auto-delete-bucket: "false"
    ibm.io/bucket: "test-bkt"
    ibm.io/secret-name: "coscredentials"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi # Enter a fictitious value

